# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
     # Developer area
     # Can build and test command and configuration.
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      
      # Do not modify below lines 
      # Google cloud setup and deployment commands
      # TODO: Nodejs + GCP SDK should be new re-usable image.
      - run:
          name: 'Install Google Cloud SDK'
          command: |
            # reference - 
            echo $DEV_GCLOUD_ACCOUNT_KEY > key.json
            wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-228.0.0-linux-x86_64.tar.gz
            tar -xf google-cloud-sdk-228.0.0-linux-x86_64.tar.gz
            CLOUDSDK_CORE_DISABLE_PROMPTS=1
            ./google-cloud-sdk/install.sh -q
            ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file key.json -q
            ./google-cloud-sdk/bin/gcloud functions deploy $APP_NAME --runtime $RUN_TIME --trigger-http --project $GCP_PROJECT_NAME